spring:
  application:
    name: hello-world

LOG_LEVEL: DEBUG
ROOT_LOG_LEVEL: ERROR
LOG_PATH_NAME: /hello-world/logs/apiexample
LOG_FILE_NAME: apiexample

logging:
  level:
    root: ${ROOT_LOG_LEVEL}
  file:
    name: ${LOG_PATH_NAME}/${LOG_FILE_NAME}.log
  pattern:
    console: '%d %clr([%-5level]) %replace(%caller{1}){"Caller\+\d	 at ",""}%msg%n'
    file: "%d [%-5level] [%thread] [%c{25}] [%method] %msg%n"
  logback:
    rollingpolicy:
      file-name-pattern: ${LOG_PATH_NAME}/${LOG_FILE_NAME}.log.%d{yyyy-MM-dd}_%i   # .gz, .zip 등을 넣으면 자동 일자별 로그파일 압축
      max-file-size: 10MB # 파일당 최대 용량 KB, MB, GB, 10MB를 넘어가면 %i 숫자 증가되면서 롤링
      max-history: 60
      total-size-cap: 1GB